# 47장 에러 처리

# 47장 에러 처리

## 47.1 에러 처리의 필요성

```tsx
const $button = document.querySelector('button') // null

// Error
$button.classList.add('disabled')
// TypeError: Cannot read property 'classList' of null

// Fixed
$button?.classList.add('disabled')
```

```tsx
const $elem = document.querySelector('#1')
// DOMException: Failed to excute 'querySelector' on 'Document': '#1' is not a valid seletor.
```

- CSS에서 ID 선택자는 숫자로 시작할 수 없다. 따라서 `#1`은 유효한 CSS 선택자가 아니다.
- 만약 `id` 속성 값이 숫자로 시작하는 요소를 선택하려면, `document.querySelector("[id='1']");`

## 47.2 try … catch … finally 문

```tsx
try {
  // 실행할 코드 (에러 발생 가능성이 있는 코드)
} catch (err) {
  // try 코드 블록에서 에러가 발생하면 이 코드 블록의 코드가 실행
  // err에는 try 코드에서 발생한 Error 객체가 전달
} finally {
  // 에러 발생과 상관없이 반드시 한 번 실행 (Optional)
}
```

## 47.3 Error 객체

```tsx
const error = new Error('invalid')
```

- Error 생성자 함수는 에러 객체를 생성한다.
- Error 생성자 함수에는 에러를 상세히 설명하는 에러 메시지를 인수로 전달할 수 있다.
- Error 생성자 함수가 생성한 에러 객체는 message, stack 프로퍼티를 갖는다.
  - message: Error 생성자 함수에 인수로 전달한 에러 메시지
  - stack: 에러를 발생시킨 콜 스택의 호출 정보를 나타내는 문자열 (디버깅 목적으로 사용)

### Error 생성자 객체

- 생성자 함수가 생성한 에러 객체의 프로토타입은 모두 Error.prototype을 상속받는다.
- Error 생성자
  - Error : 일반적 에러 객체
  - SyntaxError: 자바스크립트 문법에 맞지 않는 문을 해석할 때 발생
  - ReferenceError : 참조할 수 없는 식별자를 참조했을 때 발생
  - TypeError : 피연산자 또는 인수의 데이터 타입이 유효하지 않을 때 발생
  - RangeError : 숫자값의 허용 범위를 벗어났을 때 발생
  - URIError : encodeURL 또는 decodeURI 함수에 부적절한 인수를 전달했을 때 발생
  - EvalError : eval 함수에서 발생

## 47.4 throw 문

- Error 생성자 함수로 에러 객체를 생성한다고 에러가 발생하는 것은 아니다.
- 에러 객체 생성과 에러 발생은 의미가 다르다.

```tsx
try {
  throw new Error('something wrong')
} catch (error) {
  console.log(error)
}
```

## 47.8 에러의 전파

- 에러는 호출자 방향으로 전파된다. 즉, 콜 스택의 아래 방향으로 전파된다.
- throw된 에러를 어디에서도 캐치하지 않으면 프로그램은 강제 종료된다.
- 주의
  - 비동기 함수인 setTimeout, 프로미스 후속 처리 메서드의 콜백 함수는 호출자가 없다.
  - 태스크 큐나 마이크로태스크 큐에 일시 저장되었다가 콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 푸시되어 실행된다. 이때 콜 스택에 푸시된 콜백 함수의 실행 컨텍스트는 콜 스택의 가장 하부에 존재하게 되어 에러를 전파할 호출자가 존재하지 않는다.
  - 비동기 콜백함수 내에서는 항상 에러 처리를 해야한다.
